name: Production Deploy

concurrency:
  group: production
  cancel-in-progress: false

on:
  push:
    branches: [production]

jobs:
  Apply:
    if: "!contains(github.event.head_commit.message, 'no actions')"
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
